### PR TITLE
Fixes #187: Remove KONTINUITY_ prefix from environment variables

### LINKED ISSUE #187: Rename KONTINUITY_CATAPULT_GITHUB_APP_CLIENT_ID and KONTINUITY_CATAPULT_GITHUB_APP_CLIENT_SECRET environment variables
Remove the `KONTINUITY_` prefix

### PR DESCRIPTION
**Pull request by gastaldi**
Signed-off-by: George Gastaldi <gegastaldi@gmail.com>

### CODE REVIEW

**Comment by gastaldi** [comment]
It is also changed, what do you mean?

**Comment by gastaldi** [comment]
See https://github.com/redhat-kontinuity/catapult/pull/188/files#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by ALRubinger** [comment]
```
shouldNotHaveTokenAssociatedToStart(org.kontinuity.catapult.test.GitHubResourceIT)  Time elapsed: 1.374 sec  <<< ERROR!
com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException: 500 Internal Server Error for http://127.0.0.1:8080/api/github/verify
	at org.kontinuity.catapult.test.GitHubResourceIT.shouldNotHaveTokenAssociatedToStart(GitHubResourceIT.java:95)

redirectForAuthorizeIsRequired(org.kontinuity.catapult.test.GitHubResourceIT)  Time elapsed: 0.715 sec  <<< FAILURE!
java.lang.AssertionError: expected:<400> but was:<500>
	at org.kontinuity.catapult.test.GitHubResourceIT.redirectForAuthorizeIsRequired(GitHubResourceIT.java:139)

noManInTheMiddle(org.kontinuity.catapult.test.GitHubResourceIT)  Time elapsed: 0.67 sec  <<< FAILURE!
java.lang.AssertionError: expected:<401> but was:<500>
	at org.kontinuity.catapult.test.GitHubResourceIT.noManInTheMiddle(GitHubResourceIT.java:156)

shouldHaveTokenAssociatedAfterOAuth(org.kontinuity.catapult.test.GitHubResourceIT)  Time elapsed: 1.507 sec  <<< ERROR!
org.openqa.selenium.NoSuchElementException: 
{"errorMessage":"Unable to find element with id 'login_field'","request":{"headers":{"Accept-Encoding":"gzip,deflate","Connection":"Keep-Alive","Content-Length":"36","Content-Type":"application/json; charset=utf-8","Host":"localhost:7199","User-Agent":"Apache-HttpClient/4.3.5 (java 1.5)"},"httpVersion":"1.1","method":"POST","post":"{\"using\":\"id\",\"value\":\"login_field\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/7a856c00-0cf3-11e7-8d36-29fe96c21517/element"}}
Command duration or timeout: 392 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.42.0', revision: '5e824302019c86eae9c8c3ca9155e7307b410cf8', time: '2014-05-24 09:48:41'
System info: host: 'tubescreamer', ip: '192.168.2.83', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.10-100.fc24.x86_64', java.version: '1.8.0_74'
Driver info: org.openqa.selenium.phantomjs.PhantomJSDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, handlesAlerts=false, databaseEnabled=false, version=1.9.8, platform=LINUX, browserConnectionEnabled=false, proxy={proxyType=direct}, nativeEvents=true, acceptSslCerts=false, driverVersion=1.1.0, locationContextEnabled=false, webStorageEnabled=false, browserName=phantomjs, takesScreenshot=true, driverName=ghostdriver, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 7a856c00-0cf3-11e7-8d36-29fe96c21517
	at org.kontinuity.catapult.test.GitHubResourceIT.performGitHubOAuth(GitHubResourceIT.java:184)
	at org.kontinuity.catapult.test.GitHubResourceIT.shouldHaveTokenAssociatedAfterOAuth(GitHubResourceIT.java:118)
Caused by: org.openqa.selenium.remote.ScreenshotException: 
Screen shot has been taken
Build info: version: '2.42.0', revision: '5e824302019c86eae9c8c3ca9155e7307b410cf8', time: '2014-05-24 09:48:41'
System info: host: 'tubescreamer', ip: '192.168.2.83', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.10-100.fc24.x86_64', java.version: '1.8.0_74'
Driver info: driver.version: RemoteWebDriver
	at org.kontinuity.catapult.test.GitHubResourceIT.performGitHubOAuth(GitHubResourceIT.java:184)
	at org.kontinuity.catapult.test.GitHubResourceIT.shouldHaveTokenAssociatedAfterOAuth(GitHubResourceIT.java:118)
Caused by: org.openqa.selenium.remote.ErrorHandler$UnknownServerException: 
{"errorMessage":"Unable to find element with id 'login_field'","request":{"headers":{"Accept-Encoding":"gzip,deflate","Connection":"Keep-Alive","Content-Length":"36","Content-Type":"application/json; charset=utf-8","Host":"localhost:7199","User-Agent":"Apache-HttpClient/4.3.5 (java 1.5)"},"httpVersion":"1.1","method":"POST","post":"{\"using\":\"id\",\"value\":\"login_field\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/7a856c00-0cf3-11e7-8d36-29fe96c21517/element"}}
Build info: version: '2.42.0', revision: '5e824302019c86eae9c8c3ca9155e7307b410cf8', time: '2014-05-24 09:48:41'
System info: host: 'tubescreamer', ip: '192.168.2.83', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.10-100.fc24.x86_64', java.version: '1.8.0_74'
Driver info: driver.version: unknown


Results :

Failed tests: 
  GitHubResourceIT.noManInTheMiddle:156 expected:<401> but was:<500>
  GitHubResourceIT.redirectForAuthorizeIsRequired:139 expected:<400> but was:<500>
Tests in error: 
  GitHubResourceIT.shouldHaveTokenAssociatedAfterOAuth:118->performGitHubOAuth:184 » NoSuchElement
  GitHubResourceIT.shouldNotHaveTokenAssociatedToStart:95 » FailingHttpStatusCode

Tests run: 6, Failures: 2, Errors: 2, Skipped: 2
```

**Comment by ALRubinger** [comment]
@gastaldi Please resolve errors above

**Comment by ALRubinger** [comment]
14591ce87c4c03dc4a17eef4338714d9839d8aa3

**Pull request closed without merging**
