### PR TITLE
Corrected errors in IT reporting and optimized pipeline script

### PR DESCRIPTION
**Pull request by sabre1041**
Optimizations in Jenkins pipeline script 

* Resolve bug in IT JUnit Jenkins reports for #54 
* Reduce testing iterations
* Refactored redundant step and notification validations

Tested and validated branch in local [Jenkins environment](http://jenkins.master.distortion.example.com/job/catapult-test/2/console)

To access, add the following to `/etc/hosts` file

    10.3.10.147 jenkins.master.distortion.example.com

### CODE REVIEW

**Comment by ALRubinger** [comment]
Cool on the commits. :)

Not understanding the piece about the `hosts` file?  Can we just access via IP to keep setup more simple for devs?  Or should we map a real domain name to it?

**Comment by sabre1041** [comment]
@ALRubinger that CI environment is a bridge (a fragile one at that) until the fabric8 environment comes back or we move to the more permanent CI environment 

The environment is the fabric8 runtime on top of OSE on OpenStack. Since the OpenShift router is configured. Since it is in OSE, the environment cannot be accessed via an IP but instead a hostname. 

We could add a DNS entry for it, but given the short amount of time this environment will be used, it is probably easier to modify the `hosts` file on an individual machine

**Comment by ALRubinger** [comment]
Sorry, just another followup: the `hosts` file entry needs to be on the developer machine or on the CI environment host?  Doesn't seem to be a local developer requirement as it's in the `Jenkinsfile`, which we don't use.  If I'm wrong about this just let me know. :)

**Comment by ALRubinger** [comment]
Issue #54 
cb88ec640fb7326a0e9da9c57c88dde6c0019aa2

**Comment by sabre1041** [comment]
@ALRubinger the `hosts` file modification would occur on the developers machine in order for them to access the temporary CI environment

**Comment by ALRubinger** [comment]
Got it!  Mind making an issue to update the README, noting how to access CI
in general (which may include RHT VPN as a requirement temporarily as well)?

**Pull request closed without merging**
