### PR TITLE
Fixes #170: Read description from .obsidian/obsidian.yaml file

### LINKED ISSUE #170: When GitHub repo is created, use proper description
Expose a way to provide a description via the API.  Ideally we'd want a QuickStart description in this field in the cases we're actually creating a QuickStart.  Right now the `fling` impl is simply putting in the String "quickstart".

### PR DESCRIPTION
**Pull request by gastaldi**
- [X] Have you created an [issue](https://github.com/redhat-kontinuity/catapult/issues) and used it in the commit message?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/redhat-kontinuity/catapult/pulls) for the same issue?
- [X] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by ALRubinger** [comment]
Don't we know the name of the Obsidian descriptor file from the catalog?

**Comment by gastaldi** [comment]
Only the obsidian-addon has access to the catalog. Catapult doesn't know about it

**Comment by gastaldi** [comment]
But I guess it should perhaps be provided as part of the Projectile instead and we need to figure out some way to pass that to CatapultResource

**Comment by ALRubinger** [comment]
@gastaldi Right, TBH I'm hesitant about this because of the guesswork involved.  Let's try for something more predictable.  Passing the state into the Projectile makes more sense to me than having Catapult be aware of the obsidian descriptor or catalog.  Better separation of concerns that way.

**Comment by gastaldi** [comment]
Deal, rejecting this PR

**Pull request closed without merging**
