### PR TITLE
Fixes #152: Avoid CORS issue when reading appstore.json from Github repository

### LINKED ISSUE #152: CORS issue when accessing AppStore URL
The following error is shown when the app is accessed in Firefox: 
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://raw.githubusercontent.com/redhat-kontinuity/appstore/master/appstore.json. (Reason: CORS preflight channel did not succeed).
```

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by gastaldi** [comment]
Ok to review

**Comment by ALRubinger** [comment]
Reviewed and put into upstream/152 pending potential more revisions: https://github.com/redhat-kontinuity/catapult/commit/40818f3452a91f8f8a6b24e2f84f673b2d171b6a

**Comment by ALRubinger** [comment]
Issues identified and discussed on linked commit; awaiting new commits to address them before PR merge.

**Comment by ALRubinger** [comment]
7c90f05aac62b4c7bbc888e1bb123df9e2d2f531

**Pull request closed without merging**
