### PR TITLE
Add alternative URL for jenkins.master

### PR DESCRIPTION
**Pull request by tnozicka**
Also add jenkins.master.10.3.10.147.xip.io as an alternative serverName to http proxy server.

### CODE REVIEW

**Comment by ALRubinger** [comment]
Using this directly, I'm just seeing:

  `jenkins.master.10.3.10.147.xip.io’s server DNS address could not be found.`

Thoughts?

**Comment by sabre1041** [comment]
@ALRubinger `xip.io` DNS resolution typically fails at Red Hat offices and in some networks

**Comment by tnozicka** [comment]
@ALRubinger Can you try if **nip.io** works for you?
```
http://jenkins.master.10.3.10.147.nip.io/
```
Both work fine at least from Brno offices, Brno's VPN and RH's OS1. Although I have heard that it might sometimes fail in some RH's local networks.

**Comment by ALRubinger** [comment]
Yep, DNS resolve good enough:

```
[alr@overdrive ~]$ ping jenkins.master.10.3.10.147.nip.io
PING jenkins.master.10.3.10.147.nip.io (10.3.10.147) 56(84) bytes of data
```

...only the host is down as the CI environment is in the process of being rebuilt, and then it'll go to the ci.centos.org environment.

**Comment by tnozicka** [comment]
@ALRubinger It is up as far as I can tell. They are just blocking ping (ICMP).

```
nmap jenkins.master.10.3.10.147.nip.io

Starting Nmap 7.12 ( https://nmap.org ) at 2016-05-17 11:10 CEST
Nmap scan report for jenkins.master.10.3.10.147.nip.io (10.3.10.147)
Host is up (0.16s latency).
rDNS record for 10.3.10.147: jenkins.master.distortion.example.com
Not shown: 995 filtered ports
PORT     STATE SERVICE
22/tcp   open  ssh
53/tcp   open  domain
80/tcp   open  http
443/tcp  open  https
8443/tcp open  https-alt

Nmap done: 1 IP address (1 host up) scanned in 9.15 seconds
```

```
ping jenkins.master.10.3.10.147.nip.io
PING jenkins.master.10.3.10.147.nip.io (10.3.10.147) 56(84) bytes of data.
^C
--- jenkins.master.10.3.10.147.nip.io ping statistics ---
10 packets transmitted, 0 received, 100% packet loss, time 8999ms
```

And I can see the website.

**Comment by ALRubinger** [comment]
Interesting; from my home (not a RHT office) and while not on the VPN, I get:

```
$ nmap jenkins.master.10.3.10.147.nip.io

Starting Nmap 7.12 ( https://nmap.org ) at 2016-05-18 18:46 EDT
Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn
Nmap done: 1 IP address (0 hosts up) scanned in 3.23 seconds
```

...so as you can see I'm a bit reluctant to put in the instructions some steps that don't work for everyone.  Ideas?  Known issues with nip.io and some providers blocking their DNS magic?

**Comment by tnozicka** [comment]
@ALRubinger 
> from my home (not a RHT office) and while not on the VPN

This is because the address 10.3.10.147 is from local range and represents different servers on different networks.
My point is that the RH private address has been there long before, I am just proposing easier way to access it.

**Comment by ALRubinger** [comment]
I do not know what I was thinking.

Actually I do; I was off the VPN to keep RHT stuff from interfering with
the DNS resolution.  Which was plain stupid.

Thanks and sorry for messing that up.

**Comment by ALRubinger** [comment]
Issue #102.

ef6baa9fa020561bde5255b75e109404d2026b36

**Pull request closed without merging**
