### PR TITLE
Replace OS template json with yaml

### PR DESCRIPTION
**Pull request by vpavlin**
I think yaml is more readable for people and OpenShift does not care, so if you don't mind, I'd suggest to switch to yaml.

### CODE REVIEW

**Comment by gastaldi** [comment]
This looks good to me. @ALRubinger feel free to merge it anytime

**Comment by ALRubinger** [comment]
@gastaldi But this would still pull off Docker Hub, and we need to update it to pull from CentOS Registry, yes?

**Comment by gastaldi** [comment]
Yes, but that's a different issue. This PR only replaces the ugly JSON with
a not so pretty YAML :)

Em 9 de mar de 2017 16:50, "Andrew Lee Rubinger" <notifications@github.com>
escreveu:

**Comment by gastaldi** [comment]
@ALRubinger I just spoke with @vpavlin and he mentioned that the main problem is that registry.devshift is not pullable by public. He's doing a wonderful job in getting that sorted out somehow.

**Comment by gastaldi** [comment]
But as I said previously, that shouldn't prevent merging the PR, since it only changes the descriptor's content type

**Pull request merged**
