### PR TITLE
Issue 125 - Embed the project template

### LINKED ISSUE #125: Embed the project template
Instead of having a single, large template to create all project resource, we can rely on a smaller `Jenkinsfile` along with a `deployment-template.yaml` at the root of the GitHub repo to clone.
The remaining part is a generic template that creates a build configuration with a Jenkins pipeline strategy.
This template can be embedded in the Catapult application.

### PR DESCRIPTION
**Pull request by xcoulon**
Added an 'openshift-project-template.json' file that contains the
template to apply on the OpenShift project.
Since there's no need anymore to look-up a 'pipelinetemplate.json'
file in the GitHub repo, all references to this argument in the code
(method parameters, etc.) could be removed.
In CatapultIT, the name of the OpenShift project is overriden with
a unique name to avoid collision with existing projects.

Fixes #125

### CODE REVIEW

**Comment by xcoulon** [comment]
@ALRubinger for your reviewing pleasure ;) 
`mvn clean verify -Pit` stills fails on the last module, `catapult-tests`, for reasons that I'll need to clarify later.

**Comment by xcoulon** [comment]
@ALRubinger also, once the PR is approved and merged, we can clean the appstore since we won't need the [openshift-template-file](https://github.com/redhat-kontinuity/appstore/blob/master/appstore.json#L6) element anymore.

**Comment by ALRubinger** [comment]
Doing PR review in integration branch: https://github.com/redhat-kontinuity/catapult/tree/125

**Comment by ALRubinger** [comment]
@xcoulon So the failures I'm seeing now in "tests" module are that we're going right to the console and aren't asked to log in.  Except for the first time.  The first time, we have to log in.  After that, it just takes us to the overview page:

```
INFO: Current URL Before Login: https://10.1.2.20:8443/console/project/kitchensink-html5-mobile/overview
```

I haven't yet figured out why that might be.  Each test run is using a new process of phantomjs which has a clear cookie store and should be representing itself to the console as a new user.

**Comment by ALRubinger** [comment]
35bd30f2573e4fdc47df4b85b11e24c180d88fc1
59aef0e1137c7b5d50714ca28a0090fe9b531171
e0480baeaaf8885093f1eb6de66a8e4bdcc831db
e6c5e07fbf3eacf61b1715d8d455f02e7f8434c5

**Pull request closed without merging**
